# Generated by Django 5.2.5 on 2025-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
